# Generated by Django 3.1.2 on 2020-11-03 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import support.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RaiseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='only enter alphabet!', regex='^[a-zA-Z ]+$')])),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='', validators=[support.validator.file_size])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.issue')),
            ],
        ),
    ]
