# Generated by Django 3.1.2 on 2020-11-04 12:20

import django.core.validators
from django.db import migrations, models
import support.validator


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only enter alphabet!', regex='^[a-zA-Z ]+$')])),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(help_text='Describ your issue here.', max_length=400)),
                ('image', models.ImageField(help_text='Size should not exceed 5 MiB.', upload_to='', validators=[support.validator.file_size])),
            ],
        ),
        migrations.AlterField(
            model_name='raiserequest',
            name='description',
            field=models.CharField(help_text='Describ your issue here.', max_length=400),
        ),
        migrations.AlterField(
            model_name='raiserequest',
            name='email',
            field=models.EmailField(help_text='Optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='raiserequest',
            name='image',
            field=models.ImageField(help_text='Size should not exceed 5 MiB.', upload_to='', validators=[support.validator.file_size]),
        ),
        migrations.AlterField(
            model_name='raiserequest',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only enter alphabet!', regex='^[a-zA-Z ]+$')]),
        ),
    ]
