# Generated by Django 3.1.2 on 2020-11-05 09:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20201104_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiserequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raiserequest',
            name='description',
            field=models.CharField(help_text='Describ your issue here.', max_length=400, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
    ]
