# Generated by Django 3.1.2 on 2020-11-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiserequest',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='support.requeststatus'),
        ),
    ]
