# Generated by Django 3.1.2 on 2020-11-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_raiserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiserequest',
            name='status',
            field=models.ForeignKey(default='Open', on_delete=django.db.models.deletion.CASCADE, to='support.requeststatus'),
        ),
    ]
