# Generated by Django 3.1.2 on 2020-11-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20201105_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiserequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.requeststatus'),
        ),
    ]
