# Generated by Django 3.1.2 on 2020-11-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20201105_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiserequest',
            name='status',
        ),
    ]
