# Generated by Django 3.1.2 on 2020-11-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_raiserequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestStatus',
        ),
    ]
