# Generated by Django 3.1.3 on 2020-11-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20201111_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
