# Generated by Django 3.1.3 on 2020-11-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20201111_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiserequest',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
